name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_BACKEND: ${{ secrets.ECR_BACKEND }}
      ECR_FRONTEND: ${{ secrets.ECR_FRONTEND }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_BACKEND%/*}

      - name: Build & push backend image
        run: |
          docker build -f Dockerfile.backend -t $ECR_BACKEND:$GITHUB_SHA .
          docker push $ECR_BACKEND:$GITHUB_SHA

      - name: Build & push frontend image
        run: |
          docker build -f Dockerfile.frontend -t $ECR_FRONTEND:$GITHUB_SHA .
          docker push $ECR_FRONTEND:$GITHUB_SHA

      # Deployment step placeholder
      - name: Deploy to ECS
        run: echo "Update ECS service with new images" 