name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Run on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push backend image
      run: |
        docker build -t ${{ secrets.ECR_BACKEND }}:latest ./backend
        docker push ${{ secrets.ECR_BACKEND }}:latest

    # Optional: build frontend similarly if needed
    #- name: Build, tag, and push frontend image
    #  run: |
    #    docker build -t ${{ secrets.ECR_FRONTEND }}:latest ./frontend
    #    docker push ${{ secrets.ECR_FRONTEND }}:latest

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ./ecs/task-def.json
        service: your-ecs-service-name
        cluster: your-ecs-cluster-name
        wait-for-service-stability: true
